//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace iot { namespace SenseHatLedArray {

// Methods
public ref class SenseHatLedArrayDrawShapeCalledEventArgs sealed
{
public:
    SenseHatLedArrayDrawShapeCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ int32 interfaceMemberShapeKind);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property SenseHatLedArrayDrawShapeResult^ Result
    {
        SenseHatLedArrayDrawShapeResult^ get() { return m_result; }
        void set(_In_ SenseHatLedArrayDrawShapeResult^ value) { m_result = value; }
    }

    property int32 ShapeKind
    {
        int32 get() { return m_interfaceMemberShapeKind; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<SenseHatLedArrayDrawShapeResult^>^ GetResultAsync(SenseHatLedArrayDrawShapeCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<SenseHatLedArrayDrawShapeResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<SenseHatLedArrayDrawShapeResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    SenseHatLedArrayDrawShapeResult^ m_result;
    int32 m_interfaceMemberShapeKind;
};

public ref class SenseHatLedArrayTurnOffCalledEventArgs sealed
{
public:
    SenseHatLedArrayTurnOffCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property SenseHatLedArrayTurnOffResult^ Result
    {
        SenseHatLedArrayTurnOffResult^ get() { return m_result; }
        void set(_In_ SenseHatLedArrayTurnOffResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<SenseHatLedArrayTurnOffResult^>^ GetResultAsync(SenseHatLedArrayTurnOffCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<SenseHatLedArrayTurnOffResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<SenseHatLedArrayTurnOffResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    SenseHatLedArrayTurnOffResult^ m_result;
};

// Readable Properties
public ref class SenseHatLedArrayGetShapeRequestedEventArgs sealed
{
public:
    SenseHatLedArrayGetShapeRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property SenseHatLedArrayGetShapeResult^ Result
    {
        SenseHatLedArrayGetShapeResult^ get() { return m_result; }
        void set(_In_ SenseHatLedArrayGetShapeResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<SenseHatLedArrayGetShapeResult^>^ GetResultAsync(SenseHatLedArrayGetShapeRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<SenseHatLedArrayGetShapeResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<SenseHatLedArrayGetShapeResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    SenseHatLedArrayGetShapeResult^ m_result;
};

// Writable Properties
} } } 
