//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace iot { namespace SenseHatLedArray {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement ISenseHatLedArrayService. Instead, SenseHatLedArrayServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class SenseHatLedArrayServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] ISenseHatLedArrayService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<SenseHatLedArrayServiceEventAdapter^, SenseHatLedArrayDrawShapeCalledEventArgs^>^ DrawShapeCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<SenseHatLedArrayServiceEventAdapter^, SenseHatLedArrayDrawShapeCalledEventArgs^>^ handler) 
        { 
            return _DrawShapeCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<SenseHatLedArrayServiceEventAdapter^>(sender), safe_cast<SenseHatLedArrayDrawShapeCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _DrawShapeCalled -= token; 
        } 
    internal: 
        void raise(SenseHatLedArrayServiceEventAdapter^ sender, SenseHatLedArrayDrawShapeCalledEventArgs^ args) 
        { 
            _DrawShapeCalled(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<SenseHatLedArrayServiceEventAdapter^, SenseHatLedArrayTurnOffCalledEventArgs^>^ TurnOffCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<SenseHatLedArrayServiceEventAdapter^, SenseHatLedArrayTurnOffCalledEventArgs^>^ handler) 
        { 
            return _TurnOffCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<SenseHatLedArrayServiceEventAdapter^>(sender), safe_cast<SenseHatLedArrayTurnOffCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _TurnOffCalled -= token; 
        } 
    internal: 
        void raise(SenseHatLedArrayServiceEventAdapter^ sender, SenseHatLedArrayTurnOffCalledEventArgs^ args) 
        { 
            _TurnOffCalled(sender, args);
        } 
    }

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<SenseHatLedArrayServiceEventAdapter^, SenseHatLedArrayGetShapeRequestedEventArgs^>^ GetShapeRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<SenseHatLedArrayServiceEventAdapter^, SenseHatLedArrayGetShapeRequestedEventArgs^>^ handler) 
        { 
            return _GetShapeRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<SenseHatLedArrayServiceEventAdapter^>(sender), safe_cast<SenseHatLedArrayGetShapeRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetShapeRequested -= token; 
        } 
    internal: 
        void raise(SenseHatLedArrayServiceEventAdapter^ sender, SenseHatLedArrayGetShapeRequestedEventArgs^ args) 
        { 
            _GetShapeRequested(sender, args);
        } 
    }

    // Property Write Events
    // ISenseHatLedArrayService Implementation
    virtual Windows::Foundation::IAsyncOperation<SenseHatLedArrayDrawShapeResult^>^ DrawShapeAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ int32 interfaceMemberShapeKind);
    virtual Windows::Foundation::IAsyncOperation<SenseHatLedArrayTurnOffResult^>^ TurnOffAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<SenseHatLedArrayGetShapeResult^>^ GetShapeAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);


private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _DrawShapeCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _TurnOffCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetShapeRequested;
};

} } } 
